import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import readFileInFolder from '@/utils/read-folder'
import React from 'react';

export default function Home({ fileNames }: { fileNames: string[] }) {
  const [imageSrouce, setimageSrouce] = React.useState<number>(0);

  const handleImageClick = (id: number) => setimageSrouce(id);
  return (
    <>
      <Head>
        <title>test dev zoom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          {fileNames.map((fileName, index) => (
            <div key={fileName} onClick={() => handleImageClick(index)}>
              <Image src={`/assets/${fileName}`} alt={fileName} width={300} height={300} />
            </div>
          ))}
        </div>
        <div className={styles.content}>
          <Image src={`/assets/${fileNames[imageSrouce]}`} alt={fileNames[imageSrouce]} width={500} height={500} />
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const fileNames = readFileInFolder('public/assets')
  return {
    props: {
      fileNames
    }
  }
}
